name: "Panther Link"
description: "A secure, encrypted data tunnel."
version: "1.0.12"
slug: "panther-link"
init: false
arch:
  - aarch64
  - amd64
host_network: true
ingress: true
ingress_port: 8689
panel_icon: mdi:shield-link-variant-outline
image: "ghcr.io/panther-ha/{arch}-panther-link"
map:
  - type: addon_config
    read_only: false
options:
  debug: false
schema:
  debug: bool