name: "Panther Link"
description: "Data tunnel"
version: "1.0.0"
slug: "panther-link"
init: false
arch:
  - aarch64
  - amd64
host_network: true
image: "ghcr.io/panther-ha/{arch}-panther-link"
map:
  - type: addon_config
    read_only: false
